coordinates:
  name: eslint-config-airbnb-base
  provider: npmjs
  type: npm
revisions:
  15.0.0:
    described:
      sourceLocation:
        name: javascript
        namespace: airbnb
        provider: github
        revision: 58e6cd323ad1d010e81fb5d064a40c35e5370556
        type: git
        url: 'https://github.com/airbnb/javascript/commit/58e6cd323ad1d010e81fb5d064a40c35e5370556'
