coordinates:
  name: armkubernetesconfiguration
  namespace: github.com%2Fazure%2Fazure-sdk-for-go%2Fsdk%2Fresourcemanager%2Fkubernetesconfiguration
  provider: golang
  type: go
revisions:
  v1.1.1:
    licensed:
      declared: MIT
