coordinates:
  name: sp-application-base
  namespace: '@microsoft'
  provider: npmjs
  type: npm
revisions:
  1.10.0:
    licensed:
      declared: OTHER
  1.8.2:
    licensed:
      declared: OTHER
  1.9.1:
    licensed:
      declared: OTHER
