coordinates:
  name: dependabot-hex
  provider: rubygems
  type: gem
revisions:
  0.162.0:
    licensed:
      declared: OTHER
  0.162.1:
    licensed:
      declared: OTHER
  0.162.2:
    licensed:
      declared: OTHER
