coordinates:
  name: Microsoft.ApplicationInsights.Web
  provider: nuget
  type: nuget
revisions:
  1.2.1:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT
  2.7.2:
    licensed:
      declared: MIT
