coordinates:
  name: Microsoft.Extensions.Configuration
  provider: nuget
  type: nuget
revisions:
  2.0.0:
    licensed:
      declared: Apache-2.0
  2.0.1:
    licensed:
      declared: Apache-2.0
  2.1.0:
    licensed:
      declared: Apache-2.0
  2.1.0-preview1-final:
    licensed:
      declared: Apache-2.0
  2.1.0-preview2-final:
    licensed:
      declared: Apache-2.0
  2.1.1:
    licensed:
      declared: Apache-2.0
  2.2.0:
    licensed:
      declared: Apache-2.0
