coordinates:
  name: Microsoft.ApplicationInsights.Log4NetAppender
  provider: nuget
  type: nuget
revisions:
  1.2.0:
    licensed:
      declared: MIT
  1.2.6:
    licensed:
      declared: MIT
  2.0.0:
    licensed:
      declared: MIT
  2.1.0:
    licensed:
      declared: MIT
  2.2.0:
    licensed:
      declared: MIT
