coordinates:
  name: Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel
  provider: nuget
  type: nuget
revisions:
  2.5.1:
    licensed:
      declared: MIT
  2.7.2:
    licensed:
      declared: MIT
