coordinates:
  name: Microsoft.ApplicationInsights.PersistenceChannel
  provider: nuget
  type: nuget
revisions:
  0.15.0-build00179:
    licensed:
      declared: MIT
  0.16.1-build00418:
    licensed:
      declared: MIT
  0.17.0:
    licensed:
      declared: MIT
  0.17.2-build00169:
    licensed:
      declared: MIT
  1.0.0:
    licensed:
      declared: MIT
  1.1.0:
    licensed:
      declared: MIT
  1.2.0:
    licensed:
      declared: MIT
  1.2.3:
    licensed:
      declared: MIT
  2.0.0-beta3:
    licensed:
      declared: MIT
