coordinates:
  name: Microsoft.ApplicationInsights
  provider: nuget
  type: nuget
revisions:
  2.3.0:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT
  2.5.1:
    licensed:
      declared: MIT
  2.7.1:
    licensed:
      declared: MIT
  2.7.2:
    licensed:
      declared: MIT
