coordinates:
  name: Microsoft.ApplicationInsights.PerformanceCollector
  provider: nuget
  type: nuget
revisions:
  0.12.0-build17386:
    licensed:
      declared: MIT
  0.13.0-build26067:
    licensed:
      declared: MIT
  0.13.1-build00186:
    licensed:
      declared: MIT
  0.13.2-build00132:
    licensed:
      declared: MIT
  0.14.0-build20632:
    licensed:
      declared: MIT
  0.14.3-build00177:
    licensed:
      declared: MIT
