coordinates:
  name: Microsoft.ApplicationInsights.Agent.Intercept
  provider: nuget
  type: nuget
revisions:
  1.2.0:
    licensed:
      declared: MIT
  2.0.6:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT
