coordinates:
  name: Microsoft.ApplicationInsights.DependencyCollector
  provider: nuget
  type: nuget
revisions:
  1.2.1:
    licensed:
      declared: MIT
  2.4.1:
    licensed:
      declared: MIT
  2.5.1:
    licensed:
      declared: MIT
  2.6.4:
    licensed:
      declared: MIT
  2.7.2:
    licensed:
      declared: MIT
