coordinates:
  name: Swashbuckle.AspNetCore.SwaggerUI
  provider: nuget
  type: nuget
revisions:
  1.0.0:
    licensed:
      declared: MIT
  2.4.0:
    licensed:
      declared: MIT
  3.0.0:
    licensed:
      declared: MIT
