coordinates:
  name: Xam.Plugins.Settings
  provider: nuget
  type: nuget
revisions:
  3.0.1:
    licensed:
      declared: MIT
  3.1.1:
    files:
      - attributions:
          - Copyright (c) 2017 James Montemagno
        license: ''
        path: Xam.Plugins.Settings.nuspec
    licensed:
      declared: MIT
