  
name: 'Check for merge conflicts'
on:
  push:
    branches:
      - '**'
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 15
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'has conflicts'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
