coordinates:
  name: client_model
  namespace: github.com%2Fprometheus
  provider: golang
  type: go
revisions:
  v0.0.0-20180712105110-5c3871d89910:
    licensed:
      declared: Apache-2.0
  v0.0.0-20190115171406-56726106282f:
    licensed:
      declared: Apache-2.0
